#if FLEX_FLUID_SURFACE_FACTORY
Texture2D FlexFluidSurfaceThicknessTexture;
SamplerState FlexFluidSurfaceThicknessTextureSampler;
#endif

// Returns thickness provided for flex fluid surface rendering
float CalcFlexFluidSurfaceThicknessForMaterialNode(float2 ScreenUV)
{
#if FLEX_FLUID_SURFACE_FACTORY
	return Texture2DSampleLevel(FlexFluidSurfaceThicknessTexture, FlexFluidSurfaceThicknessTextureSampler, ScreenUV, 0);
#else
	return 0.0f;
#endif
}
